# Generated by Django 5.2.8 on 2026-02-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReadSensors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_1", models.FloatField()),
                ("sensor_2", models.FloatField()),
                ("sensor_3", models.FloatField()),
                ("sensor_4", models.FloatField()),
                ("sensor_5", models.FloatField()),
                ("sensor_6", models.FloatField()),
                ("dia", models.DateField(auto_now_add=True)),
                ("hora", models.TimeField(auto_now_add=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
